version: 0.2
phases:
  install:
    commands:
      - pip install awscli 
      - wget "https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb"
      - sudo dpkg -I hugo*.deb -y 
      - sudo apt-get -f install -y 
      - hugo version

  build:
    commands:
      - echo Entered the build phase ...
      - rm -rf public
      - hugo
  
  post_build:
    commands:
       - echo Build phase started...
       - .local/bin/aws aws s3 sync public/ s3://esaleatorio.com --delete
       - ./local/bin/aws cloudfront create-invalidation --distribution-id E29K42285AKVEE --paths '/*'
       - echo Entered the post_build phase..
       - echo Build completed on `date`
  
