version: 0.2
phases:
  install:
    commands:
    # The update and upgrade lines are commented out because the build currently takes 9 minutes
      - apt-get update && apt-get upgrade -y 
      - apt-get install python3-dev python3-pip python3-pygments git git-lfs golang -y 
      - pip3 install awscli --user
    finally:

  build:
    commands:
      - echo Entered the build phase ...
      - go get github.com/gohugoio/hugo
      - hugo version
      - rm -rf public
      - git rm -r --cache themes/terminal
      - rm -rf themes
      - git clone https://github.com/panr/hugo-theme-terminal.git themes/terminal
      - ls themes
      - hugo
      - ls 
      - pwd
  
  post_build:
    commands:
      - echo Build phase started...
      - ls
      - pwd 
      - aws s3 sync public/ s3://esaleatorio.com  --delete --acl public-read 
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E29K42285AKVEE --paths '/*'
    finally:
      - echo Entered the post_build phase..
      - echo Build completed on `date`
