version: 0.2
phases:
  install:
    commands:
      - pip install awscli 
      - wget "https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb"
      - sudo dpkg -i ./hugo*.deb
    finally:
      - hugo version

  build:
    commands:
      - echo Entered the build phase ...
      - rm -rf public
      - pwd
      - cd esaleatorio.com/aleatorio/
      - hugo
  
  post_build:
    commands:
      - cd .. 
      - echo Build phase started...
      - aws aws s3 sync public/ s3://esaleatorio.com --delete --acel public-read
      - aws cloudfront create-invalidation --distribution-id E29K42285AKVEE --paths '/*'
    finally:
      - echo Entered the post_build phase..
      - echo Build completed on `date`
  
