version: 0.2

install:
  - echo Entered the install phase...
 # - pip install --user awscli
  - wget github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
  - sudo apt-get install ./hugo* -y 
  - hugo version
before-script:
  - rm -rf public

script:
   - hugo
   - echo Build phase started...
   - aws s3 sync public/ s3://esaleatorio.com --acl public-read --delete
   - aws cloudfront create-invalidation --distribution-id E29K42285AKVEE --paths '/*'
   - echo Entered the post_build phase..
   - echo Build completed on `date`
branches:
  - master
