version: 0.2
phases:
  install:
    commands:
    # The update and upgrade lines are commented out because the build currently takes 9 minutes
    #  - apt update
    #  - apt upgrade -y 
      - apt install python3-dev python3-pip -y 
      - pip3 install Pygments --user
      - pip3 install awscli --user
      - apt install hugo -y 
    finally:

  build:
    commands:
      - echo Entered the build phase ...
      - hugo version
      - rm -rf public
      - ls 
      - hugo -v
      - ls 
      - pwd
  
  post_build:
    commands:
      - echo Build phase started...
      - ls
      - pwd 
      - aws s3 sync public/ s3://esaleatorio.com  --delete --acl public-read 
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E29K42285AKVEE --paths '/*'
    finally:
      - echo Entered the post_build phase..
      - echo Build completed on `date`
