version: 0.2
phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get upgrade -y 
      - sudo apt-get install python3-dev python3-pip
      - pip3 install awscli 
    finally:

  build:
    commands:
      - echo Entered the build phase ...
      - ls 
      - pwd
  
  post_build:
    commands:
      - echo Build phase started...
      - ls
      - pwd 
      - aws s3 sync public/ s3://esaleatorio.com  --delete --acl public-read 
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E29K42285AKVEE --paths '/*'
    finally:
      - echo Entered the post_build phase..
      - echo Build completed on `date`
