version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - sudo apt install python3 -y
      - python3-pip install awscli --upgrade --user 
      - awscli --version
      - wget github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
      - sudo apt-get install ./hugo* -y 
      - hugo version

  build:
    commands:
      - echo Entered the build phase ...
      - rm -rf public
      - hugo
  
  post_build:
    commands:
       - echo Build phase started...
       - aws s3 sync public/ s3://esaleatorio.com --delete
       - aws cloudfront create-invalidation --distribution-id E29K42285AKVEE --paths '/*'
       - echo Entered the post_build phase..
       - echo Build completed on `date`
  
